---
# Start with a '/' for absolute paths. Otherwise we assume this is relative to
# Rails.root
data_dir: 'data'
records_per_file: 50000
dump_types:
- label: 'All Records'
  constant: 'ALL_RECORDS'
- label: 'Changed Records'
  constant: 'CHANGED_RECORDS'
- label: 'All Holding IDs'
  constant: 'HOLDING_IDS'
- label: 'All Bib IDs'
  constant: 'BIB_IDS'

dump_file_types:
- label: 'Updated Records'
  constant: 'UPDATED_RECORDS'
- label: 'New Records'
  constant: 'NEW_RECORDS'
- label: 'All Holding IDs'
  constant: 'HOLDING_IDS'
- label: 'All Bib IDs'
  constant: 'BIB_IDS'
